### ISSUE TITLE
KeyError: 'n_mfcc'

### ISSUE THREAD

**Issue by zyb8543d** [yeyupiaoling/AudioClassification-Pytorch#16]
```
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    trainer = MAClsTrainer(configs=args.configs, use_gpu=args.use_gpu)
  File "/data/disk1/ybZhang/AudioClassification-Pytorch/macls/trainer.py", line 67, in __init__
    self.audio_featurizer = AudioFeaturizer(feature_conf=self.configs.feature_conf, **self.configs.preprocess_conf)
  File "/data/disk1/ybZhang/AudioClassification-Pytorch/macls/data_utils/featurizer.py", line 28, in __init__
    n_mfcc=self._feature_conf.n_mfcc,
KeyError: 'n_mfcc'
```

**Comment by yeyupiaoling** [comment]
参考这个修改配置文件。

```
preprocess_conf:
  # 音频预处理方法，支持：MelSpectrogram、Spectrogram、MFCC
  feature_method: 'MFCC'

# MFCC的参数，其他的预处理方法查看对应API设设置参数
feature_conf:
  sample_rate: 16000
  n_fft: 1024
  hop_length: 320
  win_length: 1024
  f_min: 50.0
  f_max: 14000.0
  n_mels: 64
  n_mfcc: 40
```

**Comment by zyb8543d** [comment]
解决了，感谢
